"""Tests for ohbs-image quickstart — provisioning, config handoff, cleanup,
and the single-file .pyz distribution."""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

from ohbs_image import ConfigError
from ohbs_image._quickstart import (
    _normalize_ingress_cidr,
    _resource_path,
    _security_group_ingress,
    _vpc_cidr_for,
    cmd_quickstart,
)

REPO_ROOT = Path(__file__).resolve().parent.parent


def _args(target: str, **overrides: object) -> argparse.Namespace:
    base = {
        "profile": "ubuntu2204", "region": "ap-guangzhou", "zone": "",
        "level": 1, "target": target, "force": False,
        "vpc": "", "subnet": "", "security_group": "", "instance_type": "",
        "ingress_cidr": "203.0.113.7/32",
        "dry_run": False, "yes": False, "cleanup": False,
    }
    base.update(overrides)
    return argparse.Namespace(**base)


def _set_creds(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("TENCENTCLOUD_SECRET_ID", "AKIDtest")
    monkeypatch.setenv("TENCENTCLOUD_SECRET_KEY", "test")


class _FakeCloud:
    """Serves canned TC3 responses; records every (service, action) call."""

    def __init__(self, zones: tuple[str, ...] = ("ap-guangzhou-3",)) -> None:
        self.zones = zones
        self.actions: list[tuple[str, dict]] = []

    def __call__(self, service: str, action: str, version: str, region: str,
                 params: dict, sid: str, key: str, tok: str | None = None):
        self.actions.append((action, params))
        if action == "DescribeZones":
            return {"Response": {"ZoneSet": [
                {"Zone": z, "ZoneState": "AVAILABLE"} for z in self.zones]}}
        if action == "CreateVpc":
            return {"Response": {"Vpc": {"VpcId": "vpc-qsvpc"}}}
        if action == "CreateSubnet":
            return {"Response": {"Subnet": {"SubnetId": "subnet-qssub"}}}
        if action == "CreateSecurityGroup":
            return {"Response": {"SecurityGroup": {"SecurityGroupId": "sg-qssg"}}}
        if action in ("CreateSecurityGroupPolicies", "DeleteSecurityGroup",
                      "DeleteSubnet", "DeleteVpc"):
            return {"Response": {}}
        raise AssertionError(f"unexpected TC3 action {action}")


def _patch_discovery(monkeypatch: pytest.MonkeyPatch,
                     images: list[dict] | None = None,
                     instance_types: list[dict] | None = None) -> None:
    def fake_discover(kind: str, region: str, **kw):
        if kind == "images":
            if images is not None:
                return images  # empty list = no matching source image
            return [{
                "id": "img-src1", "name": "Ubuntu 22.04",
                "state": "NORMAL", "created_at": "2026-08-01T00:00:00Z"},
                {"id": "img-src2", "name": "Ubuntu 22.04 x64",
                 "state": "NORMAL", "created_at": "2026-08-05T00:00:00Z"}]
        if kind == "instance-types":
            if instance_types is not None:
                return instance_types
            return [{
                "id": "S5.MEDIUM2", "cpu": 2, "memory": 4,
                "status": "AVAILABLE"}]
        return []
    monkeypatch.setattr("ohbs_image._quickstart.discover_resources",
                        fake_discover)


class TestQuickstartProvision:
    def test_provisions_writes_config_and_hands_off(self, tmp_path,
                                                    monkeypatch):
        cloud = _FakeCloud()
        monkeypatch.setattr("ohbs_image._tc3_api", cloud)
        _patch_discovery(monkeypatch)
        _set_creds(monkeypatch)
        chain: list[list[str]] = []
        monkeypatch.setattr(
            "ohbs_image.main",
            lambda argv: (chain.append(list(argv)), 0)[1])

        target = tmp_path / "ohbs-image.toml"
        assert cmd_quickstart(_args(str(target))) == 0

        cfg = target.read_text(encoding="utf-8")
        assert 'profile = "ubuntu2204"' in cfg
        assert 'zone = "ap-guangzhou-3"' in cfg
        assert 'instance_type = "S5.MEDIUM2"' in cfg
        assert 'source_image_id = "img-src2"' in cfg  # newest wins
        assert 'vpc_id = "vpc-qsvpc"' in cfg
        assert 'subnet_id = "subnet-qssub"' in cfg
        assert 'security_group_id = "sg-qssg"' in cfg
        assert "associate_public_ip = true" in cfg
        assert "# Generated by ohbs-image quickstart" in cfg

        # chain: doctor -> plan; build only with --yes
        assert chain == [
            ["doctor", "--config", str(target)],
            ["plan", "--config", str(target)],
        ]

        record = json.loads(
            (tmp_path / "ohbs-image.toml.quickstart.json").read_text())
        assert record["resources"] == {
            "vpc_id": "vpc-qsvpc",
            "subnet_id": "subnet-qssub",
            "security_group_id": "sg-qssg",
        }
        # linux ingress opens SSH 22
        policies = [p for a, p in cloud.actions
                    if a == "CreateSecurityGroupPolicies"]
        assert len(policies) == 1
        assert policies[0]["SecurityGroupPolicySet"]["Ingress"] == [
            {"Protocol": "TCP", "Port": "22",
             "CidrBlock": "203.0.113.7/32", "Action": "ACCEPT"}]

    def test_dry_run_creates_nothing(self, tmp_path, monkeypatch):
        cloud = _FakeCloud()
        monkeypatch.setattr("ohbs_image._tc3_api", cloud)
        _patch_discovery(monkeypatch)
        _set_creds(monkeypatch)

        target = tmp_path / "ohbs-image.toml"
        assert cmd_quickstart(_args(str(target), dry_run=True)) == 0
        assert [a for a, _ in cloud.actions] == ["DescribeZones"]  # read-only
        assert not target.exists()
        assert not (tmp_path / "ohbs-image.toml.quickstart.json").exists()

    def test_reuses_explicit_resources_without_provisioning(self, tmp_path,
                                                            monkeypatch):
        cloud = _FakeCloud()
        monkeypatch.setattr("ohbs_image._tc3_api", cloud)
        _patch_discovery(monkeypatch)
        _set_creds(monkeypatch)
        monkeypatch.setattr("ohbs_image.main", lambda argv: 0)

        target = tmp_path / "ohbs-image.toml"
        args = _args(str(target), vpc="vpc-owned", subnet="subnet-owned",
                     security_group="sg-owned")
        assert cmd_quickstart(args) == 0
        assert [a for a, _ in cloud.actions] == ["DescribeZones"]  # no Create*
        cfg = target.read_text(encoding="utf-8")
        assert 'vpc_id = "vpc-owned"' in cfg
        # nothing was created -> no resource record
        assert not (tmp_path / "ohbs-image.toml.quickstart.json").exists()

    def test_refuses_overwrite_without_force(self, tmp_path, monkeypatch):
        target = tmp_path / "ohbs-image.toml"
        target.write_text("owned", encoding="utf-8")
        assert cmd_quickstart(_args(str(target))) == 1
        assert target.read_text(encoding="utf-8") == "owned"

    def test_partial_reuse_arguments_rejected(self, tmp_path, monkeypatch):
        _set_creds(monkeypatch)
        assert cmd_quickstart(
            _args(str(tmp_path / "ohbs-image.toml"), vpc="vpc-x")) == 2

    def test_requires_scoped_ingress_for_created_networking(self, tmp_path,
                                                            monkeypatch):
        _set_creds(monkeypatch)
        assert cmd_quickstart(_args(str(tmp_path / "ohbs-image.toml"),
                                    ingress_cidr="")) == 2

    def test_requires_credentials(self, tmp_path, monkeypatch):
        monkeypatch.delenv("TENCENTCLOUD_SECRET_ID", raising=False)
        monkeypatch.delenv("TENCENTCLOUD_SECRET_KEY", raising=False)
        assert cmd_quickstart(
            _args(str(tmp_path / "ohbs-image.toml"))) == 2

    def test_missing_source_image_fails_before_provisioning(self, tmp_path,
                                                            monkeypatch):
        cloud = _FakeCloud()
        monkeypatch.setattr("ohbs_image._tc3_api", cloud)
        _patch_discovery(monkeypatch, images=[])
        _set_creds(monkeypatch)
        assert cmd_quickstart(
            _args(str(tmp_path / "ohbs-image.toml"))) == 2
        assert [a for a, _ in cloud.actions] == ["DescribeZones"]  # no Create* before source
        assert not (tmp_path / "ohbs-image.toml").exists()

    def test_yes_chains_build(self, tmp_path, monkeypatch):
        cloud = _FakeCloud()
        monkeypatch.setattr("ohbs_image._tc3_api", cloud)
        _patch_discovery(monkeypatch)
        _set_creds(monkeypatch)
        chain: list[list[str]] = []
        monkeypatch.setattr(
            "ohbs_image.main",
            lambda argv: (chain.append(list(argv)), 0)[1])
        target = tmp_path / "ohbs-image.toml"
        assert cmd_quickstart(_args(str(target), yes=True)) == 0
        assert chain[-1] == ["build", "--config", str(target), "--yes"]

    def test_windows_profile_opens_winrm_ports(self):
        assert [p["Port"] for p in _security_group_ingress(
            "win2022", "10.0.0.0/8")] \
            == ["5985", "5986"]
        assert [p["Port"] for p in _security_group_ingress(
            "ubuntu2204", "10.0.0.0/8")] \
            == ["22"]

    def test_ingress_cidr_is_normalized_and_world_open_is_rejected(self):
        assert _normalize_ingress_cidr("203.0.113.7") == "203.0.113.7/32"
        with pytest.raises(ConfigError, match="0.0.0.0/0"):
            _normalize_ingress_cidr("0.0.0.0/0")

    def test_provisioning_failure_rolls_back_recorded_resources(self, tmp_path,
                                                               monkeypatch):
        cloud = _FakeCloud()

        def fail_after_vpc(service, action, version, region, params, sid, key,
                           tok=None):
            if action == "CreateSubnet":
                cloud.actions.append((action, params))
                raise ConfigError("subnet quota exhausted")
            return cloud(service, action, version, region, params, sid, key, tok)

        monkeypatch.setattr("ohbs_image._tc3_api", fail_after_vpc)
        _patch_discovery(monkeypatch)
        _set_creds(monkeypatch)
        target = tmp_path / "ohbs-image.toml"

        assert cmd_quickstart(_args(str(target))) == 1
        assert [action for action, _ in cloud.actions][-1] == "DeleteVpc"
        assert not _resource_path(target).exists()

    def test_vpc_cidr_is_stable_per_region(self):
        assert _vpc_cidr_for("ap-guangzhou") == _vpc_cidr_for("ap-guangzhou")
        assert _vpc_cidr_for("ap-guangzhou").endswith("/16")


class TestQuickstartCleanup:
    def _write_record(self, tmp_path: Path) -> Path:
        target = tmp_path / "ohbs-image.toml"
        record = _resource_path(target)
        record.write_text(json.dumps({
            "schema": "https://ohbs-image.dev/quickstart-resources/v1",
            "region": "ap-guangzhou",
            "resources": {"vpc_id": "vpc-x", "subnet_id": "subnet-x",
                          "security_group_id": "sg-x"},
        }), encoding="utf-8")
        return target

    def test_deletes_in_reverse_dependency_order(self, tmp_path,
                                                 monkeypatch):
        target = self._write_record(tmp_path)
        cloud = _FakeCloud()
        monkeypatch.setattr("ohbs_image._tc3_api", cloud)
        _set_creds(monkeypatch)
        assert cmd_quickstart(_args(str(target), cleanup=True)) == 0
        assert [a for a, _ in cloud.actions] == [
            "DeleteSecurityGroup", "DeleteSubnet", "DeleteVpc"]
        assert not _resource_path(target).exists()

    def test_tolerates_missing_record(self, tmp_path, monkeypatch):
        target = tmp_path / "ohbs-image.toml"
        assert cmd_quickstart(_args(str(target), cleanup=True)) == 1

    def test_keeps_record_when_a_delete_fails(self, tmp_path, monkeypatch):
        target = self._write_record(tmp_path)
        calls = []
        def flaky(service, action, version, region, params, sid, key,
                  tok=None):
            calls.append(action)
            if action == "DeleteSubnet":
                from ohbs_image import ConfigError
                raise ConfigError("ResourceNotFound: subnet-x")
            return {"Response": {}}
        monkeypatch.setattr("ohbs_image._tc3_api", flaky)
        _set_creds(monkeypatch)
        assert cmd_quickstart(_args(str(target), cleanup=True)) == 1
        # sg deleted, subnet failed -> vpc still attempted? no: vpc delete
        # needs empty subnet, so we attempt it anyway (API returns 400) —
        # the record must survive for a retry.
        assert calls == ["DeleteSecurityGroup", "DeleteSubnet", "DeleteVpc"]
        assert _resource_path(target).exists()


class TestZipappDistribution:
    def test_build_zipapp_produces_runnable_pyz(self, tmp_path):
        sys.path.insert(0, str(REPO_ROOT / "scripts"))
        try:
            import build_zipapp
        finally:
            sys.path.remove(str(REPO_ROOT / "scripts"))
        out = build_zipapp.build(tmp_path / "ohbs-image.pyz")
        assert out.is_file()
        assert out.stat().st_mode & 0o111  # executable bit set

        cache = tmp_path / "pyz-cache"
        env = dict(os.environ)
        env["OHBS_IMAGE_PYZ_CACHE"] = str(cache)
        env["HOME"] = str(tmp_path / "home")
        (tmp_path / "home").mkdir(exist_ok=True)

        result = subprocess.run(
            [sys.executable, str(out), "--version"],
            capture_output=True, text=True, env=env, timeout=120)
        assert result.returncode == 0, result.stderr
        assert "ohbs-image" in result.stdout

        # extracted cache exists and contains the launcher (not the bootstrap)
        extracted = list(cache.iterdir())
        assert len(extracted) == 1
        launcher = extracted[0] / "__main__.py"
        text = launcher.read_text(encoding="utf-8")
        assert "from ohbs_image import main" in text
        assert "zipfile" not in text  # launcher, not the bootstrap

        # second run must be a direct exec of the cached copy (no re-extract)
        result2 = subprocess.run(
            [sys.executable, str(out), "--version"],
            capture_output=True, text=True, env=env, timeout=120)
        assert result2.returncode == 0, result2.stderr
        assert "ohbs-image" in result2.stdout

    def test_built_pyz_runs_list_offline(self, tmp_path):
        """The pyz must run commands that don't touch the cloud."""
        sys.path.insert(0, str(REPO_ROOT / "scripts"))
        try:
            import build_zipapp
        finally:
            sys.path.remove(str(REPO_ROOT / "scripts"))
        out = build_zipapp.build(tmp_path / "ohbs-image.pyz")
        env = dict(os.environ)
        env["OHBS_IMAGE_PYZ_CACHE"] = str(tmp_path / "cache")
        env["HOME"] = str(tmp_path / "home")
        (tmp_path / "home").mkdir(exist_ok=True)
        result = subprocess.run(
            [sys.executable, str(out), "list", "--output", "json"],
            capture_output=True, text=True, env=env, timeout=120)
        assert result.returncode == 0, result.stderr
        assert json.loads(result.stdout)["profiles"]  # non-empty profile list
