#!/usr/bin/env python3
"""Build a single-file executable ``ohbs-image.pyz``.

ohbs-image has zero pip runtime dependencies, so the whole CLI — Python
sources AND the bundled roles/engines/catalogs — can ship as one file:

    python3 scripts/build_zipapp.py            # dist/ohbs-image.pyz
    ./dist/ohbs-image.pyz --version
    ./dist/ohbs-image.pyz quickstart --region ap-guangzhou

The archive embeds a small bootstrap ``__main__``.  Because the roles are
resolved through real filesystem paths (``Path(__file__).parent / "roles"``),
which zipimport cannot serve, the bootstrap extracts the package once to a
versioned cache (``$OHBS_IMAGE_PYZ_CACHE`` or ``~/.cache/ohbs-image/pyz``),
overwrites the extracted ``__main__.py`` with a thin launcher, and re-executes
from there; later runs exec the cached copy directly.
"""
from __future__ import annotations

import argparse
import hashlib
import pathlib
import shutil
import sys
import tempfile
import zipapp

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent

# Staged as the .pyz's __main__.py: extract (once), swap in the launcher,
# then re-exec.  The launcher is embedded here so the extracted tree never
# re-runs the bootstrap (which would loop).
_BOOTSTRAP = '''\
"""ohbs-image single-file bootstrap (generated by scripts/build_zipapp.py)."""
from __future__ import annotations

import hashlib
import os
import pathlib
import shutil
import sys
import zipfile

_LAUNCHER = """\\
import sys

from ohbs_image import main

if __name__ == "__main__":
    sys.exit(main())
"""


def _pyz_path() -> pathlib.Path:
    return pathlib.Path(__file__).resolve().parent


def main() -> int:
    pyz = _pyz_path()
    digest = hashlib.sha256(pyz.read_bytes()).hexdigest()[:16]
    cache = pathlib.Path(
        os.environ.get("OHBS_IMAGE_PYZ_CACHE", "~/.cache/ohbs-image/pyz")
    ).expanduser()
    target = cache / digest
    if not (target / "__main__.py").is_file():
        tmp = target.with_name(target.name + f".tmp-{os.getpid()}")
        try:
            shutil.rmtree(tmp, ignore_errors=True)
            tmp.mkdir(parents=True)
            with zipfile.ZipFile(pyz) as zf:
                zf.extractall(tmp)
            (tmp / "__main__.py").write_text(_LAUNCHER, encoding="utf-8")
            try:
                os.replace(tmp, target)
            except OSError:
                # lost a race with a concurrent extraction — reuse theirs
                if not (target / "__main__.py").is_file():
                    raise
        finally:
            shutil.rmtree(tmp, ignore_errors=True)
    # Keep the cache from accumulating stale extractions (one per pyz build).
    try:
        entries = sorted(cache.iterdir(), key=lambda p: p.stat().st_mtime)
    except OSError:
        entries = []
    for stale in entries[:-3]:
        if stale != target:
            shutil.rmtree(stale, ignore_errors=True)
    os.execv(sys.executable,
             [sys.executable, str(target / "__main__.py"), *sys.argv[1:]])


if __name__ == "__main__":
    raise SystemExit(main())
'''

# The launcher embedded in _BOOTSTRAP, kept here only so the build script can
# syntax-check it before shipping (CI runs py_compile on scripts/).
_LAUNCHER = '''\
"""ohbs-image entry point (extracted by the .pyz bootstrap)."""
import sys

from ohbs_image import main

if __name__ == "__main__":
    sys.exit(main())
'''


def build(output: pathlib.Path,
          source_root: pathlib.Path = REPO_ROOT) -> pathlib.Path:
    """Create the .pyz at *output* from the package tree under *source_root*."""
    staging = pathlib.Path(tempfile.mkdtemp(prefix="ohbs-image-pyz-"))
    try:
        shutil.copytree(
            source_root / "ohbs_image", staging / "ohbs_image",
            ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
        (staging / "__main__.py").write_text(_BOOTSTRAP, encoding="utf-8")
        output.parent.mkdir(parents=True, exist_ok=True)
        zipapp.create_archive(staging, output,
                              interpreter="/usr/bin/env python3",
                              compressed=True)
        output.chmod(0o755)
        return output
    finally:
        shutil.rmtree(staging, ignore_errors=True)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-o", "--output",
        default=str(REPO_ROOT / "dist" / "ohbs-image.pyz"))
    args = parser.parse_args(argv)
    out = build(pathlib.Path(args.output))
    digest = hashlib.sha256(out.read_bytes()).hexdigest()
    print(f"Built {out} ({out.stat().st_size:,} bytes, sha256 {digest})")
    print(f"Run: chmod +x {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
