schema_version = 1

[build]
profile = "ubuntu2004"
region = "ap-guangzhou"
zone = "ap-guangzhou-6"
instance_type = "S5.MEDIUM2"
source_image_id = "img-22trbn9x"
vpc_id = "vpc-2t04tnm1"
subnet_id = "subnet-7c0dyr7g"
security_group_id = "sg-eaw1crvt"
associate_public_ip = true

[image]
name_prefix = "ubuntu2004-cis"
copy_regions = []

[ohbs]
level = 1

[cloud]
secret_id_env = "TENCENTCLOUD_SECRET_ID"
secret_key_env = "TENCENTCLOUD_SECRET_KEY"

[meta]
os_tag = "ubuntu-20.04"
benchmark = "CIS-v3.0.0"
